[log]
  level = "INFO"

[entryPoints]
  [entryPoints.dns]
    address = ":53"

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http]
      [entryPoints.http.http.redirections]
        [entryPoints.http.http.redirections.entrypoint]
          to = "https"
          scheme = "https"

  [entryPoints.https]
    address = ":443"

  [entryPoints.dnsovertls]
    address = ":853"

  [entryPoints.udpdns]
    address = ":53/udp"

[api]
  dashboard = true
  insecure = false

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
  [providers.docker]
    watch = true
    exposedbydefault = false
    endpoint = "unix:///var/run/docker.sock"
#   endpoint = "tcp://dockerproxy:2375"
    network = "traefik"

[certificatesResolvers.letsencrypt.acme]
  email = "mrnobody@mrnobody.com"
  storage = "/etc/traefik/acme.json"
  #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.letsencrypt.acme.dnsChallenge]
    provider = "duckdns"
    delayBeforeCheck = 0
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
